replaced_words:
  type: list
  default: 'fuck,fork|suck,soak|dick,deck|bitch,bench|cock,cork|ass,ash'
excluded_tags:
  type: list
  list_type: compact
  default: 'code|pre'
excluded_classes:
  type: list
  list_type: compact
  default: 'onebox'
